FROM docker.io/almalinux:9.5

ENV PATH=/usr/lib64/openmpi/bin:${PATH}
ENV LD_LIBRARY_PATH=/usr/lib64/openmpi/lib:${LD_LIBRARY_PATH}
ENV OMPI_ALLOW_RUN_AS_ROOT=1
ENV OMPI_ALLOW_RUN_AS_ROOT_CONFIRM=1

RUN dnf update -y && \
    dnf install -y openmpi-devel python3-pip python3-devel && \
    python3 -m pip install -qU pip mpi4py meshio matplotlib scipy

WORKDIR /app

