FROM docker.io/almalinux:9.5

ENV OMPI_ALLOW_RUN_AS_ROOT=1
ENV OMPI_ALLOW_RUN_AS_ROOT_CONFIRM=1

RUN dnf update -y && \
    dnf install -y dnf-plugins-core && \
    dnf config-manager --set-enabled crb && \
    dnf install -y openmpi-devel python3-pip python3-devel epel-release && \
    . /etc/profile.d/modules.sh && \
    module load mpi && \
    dnf install -y python3-mpi4py-openmpi && \
    python3 -m pip install -q meshio scipy matplotlib

WORKDIR /app

